// <auto-generated />
using System;
using CompraCertaAI.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraCertaAI.Repositorio.Migrations
{
    [DbContext(typeof(CompraCertaAIContexto))]
    [Migration("20260414022821_AdicionarPrecoOfertaProduto")]
    partial class AdicionarPrecoOfertaProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativa");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Descricao = "Eletrônicos, gadgets e acessórios tecnológicos",
                            Nome = "Tecnologia"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Descricao = "Jogos, consoles e acessórios para gamers",
                            Nome = "Games"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Descricao = "Decoração, móveis e utensílios domésticos",
                            Nome = "Casa"
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            Descricao = "Livros físicos e digitais de todos os gêneros",
                            Nome = "Livros"
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            Descricao = "Equipamentos e acessórios para saúde e atividade física",
                            Nome = "Fitness"
                        });
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.HistoricoPesquisa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Query");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SearchDate");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoPesquisas", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descricao");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImagemUrl");

                    b.Property<string>("LinkProduto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LinkProduto");

                    b.Property<string>("Loja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Loja");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NomeProduto");

                    b.Property<string>("PrecoOferta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PrecoOferta");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NomeProduto");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SenhaHash");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.UsuarioCategoria", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioCategorias", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.HistoricoPesquisa", b =>
                {
                    b.HasOne("CompraCertaAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("HistoricoPesquisas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("CompraCertaAI.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.UsuarioCategoria", b =>
                {
                    b.HasOne("CompraCertaAI.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("UsuarioCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraCertaAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioCategorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Produtos");

                    b.Navigation("UsuarioCategorias");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("HistoricoPesquisas");

                    b.Navigation("UsuarioCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
