// <auto-generated />
using System;
using CompraCertaAI.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraCertaAI.Repositorio.Migrations
{
    [DbContext(typeof(CompraCertaAIContexto))]
    partial class CompraCertaAIContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativa");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Descricao = "Eletrônicos, gadgets e acessórios tecnológicos",
                            Nome = "Tecnologia"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Descricao = "Jogos, consoles e acessórios para gamers",
                            Nome = "Games"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Descricao = "Decoração, móveis e utensílios domésticos",
                            Nome = "Casa"
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            Descricao = "Livros físicos e digitais de todos os gêneros",
                            Nome = "Livros"
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            Descricao = "Equipamentos e acessórios para saúde e atividade física",
                            Nome = "Fitness"
                        });
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.HistoricoPesquisa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Query");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SearchDate");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoPesquisas", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descricao");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImagemUrl");

                    b.Property<string>("LinkProduto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LinkProduto");

                    b.Property<string>("Loja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Loja");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NomeProduto");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NomeProduto");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Televisão inteligente com resolução 4K, HDR e acesso a streaming",
                            ImagemUrl = "",
                            LinkProduto = "https://www.amazon.com.br/s?k=smart+tv+samsung+55+4k",
                            Loja = "Amazon",
                            NomeProduto = "Smart TV Samsung 55\" 4K UHD"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Notebook com processador Intel Core i5, 8GB RAM e 256GB SSD",
                            ImagemUrl = "",
                            LinkProduto = "https://lista.mercadolivre.com.br/notebook-dell-inspiron-15",
                            Loja = "Mercado Livre",
                            NomeProduto = "Notebook Dell Inspiron 15"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Console de última geração com SSD ultrarrápido e ray tracing",
                            ImagemUrl = "",
                            LinkProduto = "https://www.magazineluiza.com.br/busca/playstation+5+slim/",
                            Loja = "Magazine Luiza",
                            NomeProduto = "PlayStation 5 Slim"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Controle sem fio com botão compartilhar e textura antiderrapante",
                            ImagemUrl = "",
                            LinkProduto = "https://www.amazon.com.br/s?k=controle+xbox+series",
                            Loja = "Amazon",
                            NomeProduto = "Controle Xbox Series S/X"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Conjunto com lençol, fronha e capa de almofada em percal egípcio",
                            ImagemUrl = "",
                            LinkProduto = "https://shopee.com.br/search?keyword=jogo+de+lencol+queen+percal+400",
                            Loja = "Shopee",
                            NomeProduto = "Jogo de Lençol Queen Percal 400 Fios"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Liquidificador com 900W, 5 velocidades e jarra de vidro de 2L",
                            ImagemUrl = "",
                            LinkProduto = "https://www.magazineluiza.com.br/busca/liquidificador+britania+bl900/",
                            Loja = "Magazine Luiza",
                            NomeProduto = "Liquidificador Britânia BL900"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Guia prático para escrever código limpo e de qualidade",
                            ImagemUrl = "",
                            LinkProduto = "https://www.amazon.com.br/s?k=clean+code+robert+martin",
                            Loja = "Amazon",
                            NomeProduto = "Clean Code - Robert C. Martin"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Clássico da literatura brasileira do período realista",
                            ImagemUrl = "",
                            LinkProduto = "https://lista.mercadolivre.com.br/dom-casmurro-machado-de-assis",
                            Loja = "Mercado Livre",
                            NomeProduto = "Dom Casmurro - Machado de Assis"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "Tênis esportivo com almofada de ar e palmilha macia para conforto",
                            ImagemUrl = "",
                            LinkProduto = "https://www.amazon.com.br/s?k=tenis+nike+air+max+270",
                            Loja = "Amazon",
                            NomeProduto = "Tênis Nike Air Max 270"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "Par de halteres com revestimento emborrachado, ideal para musculação em casa",
                            ImagemUrl = "",
                            LinkProduto = "https://shopee.com.br/search?keyword=kit+halteres+emborrachados+10kg",
                            Loja = "Shopee",
                            NomeProduto = "Kit Halteres Emborrachados 10kg"
                        });
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SenhaHash");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.UsuarioCategoria", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioCategorias", (string)null);
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.HistoricoPesquisa", b =>
                {
                    b.HasOne("CompraCertaAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("HistoricoPesquisas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("CompraCertaAI.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.UsuarioCategoria", b =>
                {
                    b.HasOne("CompraCertaAI.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("UsuarioCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraCertaAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioCategorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Produtos");

                    b.Navigation("UsuarioCategorias");
                });

            modelBuilder.Entity("CompraCertaAI.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("HistoricoPesquisas");

                    b.Navigation("UsuarioCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
